### ISSUE TITLE
Update FAQs

### ISSUE THREAD

**Issue by stefaniehoechtl** [asterics/AsTeRICS-Ergo#8]
Update FAQs (based on the results of the evaluation)

**Comment by stefaniehoechtl** [comment]
@klues I added some FAQs. I hope I've done everything right?

**Comment by klues** [comment]
great! :+1: 
i briefly looked at them, most things were correct. you had some errors like `<b>text...<b/>` instead of `<b>text...</b>` but considering the fact that you edited this online and had no support of an text-editor you did a great job! :)

i pushed the changes you made in the branch to our online-version and you can check them here:
https://asterics.github.io/AsTeRICS-Ergo/mock.html#!/home/envcontrol/help/faq/

some tips for the future that may make your life easier:
* https://jsfiddle.net/ds0opf5e/ <-- here you can paste your html on the left side and by clicking on "run" you see the result, how it will look like in AsTeRICS-Ergo on the right side. Additionally you can click on "tidy" to nicely format your code automatically. --> http://prntscr.com/gtwwas
* as you see jsfiddle also automatically colors things red, that are errors. in the example in the link the last `</p>` is red. this is because a `<p>`-element (paragraph) must not contain a list (`<ul>`). This is something also I did not know ;) I already replaced the `<p>` with a `<div>` (a general container element in html) in these cases in your new FAQs. 
* https://html-online.com/editor/ is a nice online-html editor where you can write like in Word on the left and get the HTML on the right. You could use this to beautify the format of some FAQ-Answers (If you like - do not spend too much time, it is not neccesary, that they are formatted perfectly ;)). You can also paste the existing HTML on the right to start with.

PS: I saw that in some Answers links are missing where you wrote LINKS. It would be great if you write at all places where I should do something "TODO" so that I am able to find these things quickly.

**Comment by stefaniehoechtl** [comment]
Thank you very much for these tips & links. 
That helps a lot. :)

**Comment by klues** [comment]
open FAQ: how to use smartphone. maybe use this technology:
https://www.whatismybrowser.com/detect/what-is-my-local-ip-address
to get own local IP and show link/QR-code to connect

**Comment by deinhofer** [comment]
Question: how to control Asterics Ergo from Smartphone still missing.

**Comment by klues** [comment]
merged https://github.com/asterics/AsTeRICS-Ergo/pull/96

**Comment by klues** [comment]
@stefaniehoechtl please add a FAQ describing issues with AntiVirus programs

**Comment by klues** [comment]
added FAQ describing how to use AsTeRICS-Ergo with a smartphone with: https://github.com/asterics/AsTeRICS-Ergo/pull/102

looks like this:
https://asterics.github.io/AsTeRICS-Ergo/mock.html#!/home/envcontrol/help/faq/38
(of course with online-version it does not work to connect with smartphone)

problems:
* detecion of local IP only works in Chrome and Firefox, not in Edge or IE
* Win 10 firewall by default blocks requests from tablet/smartphone to PC to show AsTeRICS-Ergo
--> opened this ticket with ideas to resolve these issues: https://github.com/asterics/AsTeRICS-Ergo/issues/101

**Comment by klues** [comment]
so the only remaining missing FAQ is the one describing antivirus-issues, @stefaniehoechtl please add it. afterwards we can close this issue :)

**Comment by stefaniehoechtl** [comment]
I added the FAQ regarding the antivirus programs to the master branch.

**Comment by stefaniehoechtl** [comment]
@klues 
**I reviewed the FAQs – could you please add the following links / illustrations? (changes concern the German and English FAQs)**
**Question 1** (Which devices can be controlled using AsTeRICS Ergo?) --> **add links** 
**Question 14** (I set up a device (e.g. TV, DVD player, ambient light, radio / CD player) using the IrTrans. However, it is not possible to control it using AsTeRICS Ergo. What shall I do?) --> **I would add illustrations for better understanding?** 
**Question 15** (I set up a device (e.g. TV, DVD player, ambient light, radio / CD player) using the IrTrans. I can control the environment using AsTeRICS Ergo. However, some commands do not work properly. What shall I do?) --> **I would add illustrations for better understanding?**
**Question 28** (Where can I purchase the required hardware?) --> **add links** of possible providers
**Question 38** (How is it possible to use AsTeRICS-Ergo on a Smartphone or Tablet?) --> **add 9081**? (the user needs to enter the IP-address:9081)

**If you think that some of these changes are not useful, please tell me, so I can delete the text “(TODO…)”.**

**Comment by deinhofer** [comment]
I checked your link showing the ip-address FAQ:
https://asterics.github.io/AsTeRICS-Ergo/mock.html#!/home/envcontrol/help/faq/38

On my chrome browser only the IP-address is shown, but not the whole link. Shouldn't it show the whole  URL including the port numbers? e.g. http://<ip>:<port>/

**Comment by klues** [comment]
@ FAQ 38, @deinhofer:
yes, on github.io the port is missing, because my code uses the current port of the website (which is empty on github.io). locally it works.
but I will add a fallback, so that also online the port is shown.

the qr-code includes the whole link, with `http://`, but on the text I did not show `http://` because all browsers do correctly add it, if you just type the IP manually.

**Comment by klues** [comment]
@stefaniehoechtl 
fixed your recommendations with https://github.com/asterics/AsTeRICS-Ergo/pull/104
check it here: https://asterics.github.io/AsTeRICS-Ergo/mock.html#!/home/envcontrol/help/faq/

i think we can close this issue now :)
